# Generated by Django 6.0.6 on 2026-07-02 11:02

import game.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_room_code, editable=False, max_length=8, unique=True)),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('move_history_san', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=10)),
                ('looking_for_match', models.BooleanField(default=False)),
                ('host_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('guest_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('host_color', models.CharField(choices=[('w', 'White'), ('b', 'Black')], default='w', max_length=1)),
                ('guest_joined', models.BooleanField(default=False)),
                ('host_connected', models.BooleanField(default=False)),
                ('guest_connected', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, choices=[('w', 'White'), ('b', 'Black')], max_length=1, null=True)),
                ('result_reason', models.CharField(blank=True, choices=[('checkmate', 'Checkmate'), ('resignation', 'Resignation'), ('stalemate', 'Stalemate'), ('draw', 'Draw'), ('abandoned', 'Abandoned')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='game_room_code_ff5339_idx')],
            },
        ),
    ]
